There was an error using OrientDB - java.lang.NoClassDefFoundError: com/googlecode/concurrentlinkedhashmap/ConcurrentLinkedHashMap. It has been fixed by adding a new 3rdpl with the needed lib. Furthermore, the JNA 3rdpl has been added. An update to OrientDB 1.7.2 has been made too.